<?php

// autoload.php @generated by Composer

require_once __DIR__ . '/composer/autoload_real.php';

$clientID = '365618096866-keg1924b8fsl8656jmk7mcmqf8acviqg.apps.googleusercontent.com';
$clientSecret ='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';
$redirectURL ='http://localhost:8888/CONGOOGLE/index.php';

//create client request to google
$client = new Google_Client();
$client->setClientID($clientID);
$client->setClientSecret($clientSecret);
$client->setRedirectURL($redirectURL);
$client->addScope('profile');
$client->addScope('email');

 if(isset($_GET['code'])){
     
 }else{
     echo "<a href='".$client->createAuthUrl()."'>Login with Google</a>" ;
 }
?>
