<?php

// autoload.php @generated by Composer

require_once __DIR__ . '/composer/autoload_real.php';

$clientID = '365618096866-keg1924b8fsl8656jmk7mcmqf8acviqg.apps.googleusercontent.com';
$clientSecret ='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';
$redirectURl ='http://localhost/CONGOOGLE/index.php';

//create client request to google
$client = new Google_Client();
$client->setClientID($clientID);
$client->setClientSecret($clientSecret);
$client->setRedirectURi($redirectURl);
$client->addScope('profile');
$client->addScope('email');

 if(isset($_GET['code'])){
     $token = $client->fetchAccessTokenWithAuthCode($_GET['code']);
     $client->setAccessToken($token);

     //Getting user profile information

     $gauth = new Google_Service_Oauth2($client);
     $google_info = $gauth->userinfo->get();
     $email= $google_info->email;
     $name= $google_info->name;

     echo"welcome ".$name." yours email is :".$email;

     
 }else{
     echo "<a href='".$client->createAuthUrl()."'>Login with Google</a>" ;
 }


